### ISSUE TITLE
Feedback for “Nested links”

### ISSUE THREAD

**Issue by qcgm1978** [kizu/kizu.github.com#175]
Why haven't you use other element instead of <a>, e.g.
```
<span data-href="#Foo">
    Foo
    <a href="#Bar">
        Bar
    </a>
    Baz
</span>
```
and bind click event to the span element?

**Comment by kizu** [comment]
Emulating links using click events would mean we wouldn't have a native link, so all the interactions that users were used to do with links wouldn't work. Users could want to open links in new windows/tabs using ket modifiers when clicking, users could want to use context menu for links, even drag-n-drop. Different tools (like screen readers, search engines etc.) won't understand such links too, unless you would provide all the proper WAI-ARIA accessibility attributes (however, my solution using object is far from perfect too — some screenreaders don't understand the fallback content for some reason).

All those issues make non-native links rather hard to use, as for the perfect user experience you'll need to implement all those things from scratch.

Also: speaking of JS: if we'd want to use JS, there is another, more simple solution — we could inject links inside links using DOM (not using innerHTML), this way the parser won't interfere and links would nest properly. This would probably solve accessibility problems, but won't solve the problem with tools that do not have JS enabled.

**Comment by qcgm1978** [comment]
I understand, thank your answer. I'll try it if possible
