### ISSUE TITLE
Отзыв на «Легенды и заголовки»

### ISSUE THREAD

**Issue by msurikov** [kizu/kizu.github.com#177]
LEGEND - это честный блок (**display: block**), причём он фактически во всех браузерах реализуется, как имеющий **width: fit-content**. Можно просто использовать **margin: 0 auto** для его центрирования и **margin: 0 0 0 auto** - для сдвига к правой границе fieldset. Разве не так?

**Comment by kizu** [comment]
Это довольно старая статья, когда я её писал intrinsic значений для размерностей ещё не существовало, а всякие особенности реализации в браузерах — были. Я давно на этот момент не смотрел, но верю, что всё стало лучше :)
