### ISSUE TITLE
Отзыв на «Попапы и дропдауны»

### ISSUE THREAD

**Issue by vitaliyzolotoy** [kizu/kizu.github.com#181]
Подскажи, пожалуйста, как работает скрытие попапа и дрордауна в этом експерименте.

**Comment by kizu** [comment]
Когда показываем попап/дропдаун, одновременно показываем над всей страницей блок-закрывашку, либо лейбл для снятия чекбокса, либо ссылку с хрефом на несуществующий якорь, в зависимости от метода вызова попапа/дропдауна. Ну и там с помощью соответствующих з-индексов всё слоями располагается.

**Comment by vitaliyzolotoy** [comment]
Понятно, спасибо.
