### ISSUE TITLE
Отзыв на «Оформление строчных блоков кода»

### ISSUE THREAD

**Issue by captain-zsa** [kizu/kizu.github.com#185]
Попробуй ещё с цветом поиграть или подчеркивание добавить. В примерах неплохо, но курсив у некоторых шрифтов не очень сильно выделяет блоки кода, хочется чуть больше визуального выделения на самом деле.

**Comment by kizu** [comment]
Как я и написал — это субъективный момент, и можно стилизовать как хочется, но учитывая специфику. Если для конкретного шрифта/кейса нужно более яркое выделение — без проблем, но по дефолту, на мой вгляд, курсива вполне достатосно :)
