### ISSUE TITLE
Feedback for “Conditions for CSS Variables”

### ISSUE THREAD

**Issue by tabatkins** [kizu/kizu.github.com#186]
Note that the rgba()/etc arguments are now defined to be number, not integer. (Browsers haven't caught up to it yet, tho.)  Or you can just use % arguments instead, as they accept any numeric value.  (This is why the integer restriction was always so stupid - `50%` doesn't even have an integer equivalent, as it's equal to `127.5`.)

**Comment by kizu** [comment]
Wow, thanks! Added a [note](http://kizu.ru/en/fun/conditions-for-css-variables/#issue-resolved) in the post about this.
