### ISSUE TITLE
Feedback for “Controlling the Specificity”

### ISSUE THREAD

**Issue by ollicle** [kizu/kizu.github.com#192]
“Loot at this example” I expect should be “Look at this example”.

Thanks for the article :)

BTW the edit on GitHub link in the footer of the article points to a broken link: <https://github.com/kizu/kizu.github.com/blob/source/src/documents/posts/2016-12-21-(fun)-controlling-the-specificity/index.en.md>

**Comment by kizu** [comment]
Thanks! Fixed the article and pushed the source of it, so it would be there at gh actually %)
