### ISSUE TITLE
Feedback for “Conditions for CSS Variables”

### ISSUE THREAD

**Issue by brunoais** [kizu/kizu.github.com#193]
Why not just use classes and apply CSS rules according to the classes applied to elements?

**Comment by kizu** [comment]
Two words: _cascade_ and _inheritance_.

Implementing things possible with cascade can be really complicated for a lot of cases, and even with preprocessors it could snowball into an unmaintainable mess.

Inheritance is a thing you just couldn't implement in any other way, including preprocessors.

Here is a nice article about what variables can do: https://css-tricks.com/difference-between-types-of-css-variables/, there are also links to videos of some talks at the bottom of it, I highly recommend the one by Lea Verou.

**Comment by brunoais** [comment]
I've seen those.
CSS variables are great, I have no doubt about that.
What I'm wondering is why not use classes instead of trying to make pseudo `if`?

**Comment by kizu** [comment]
Because its CSS Variables, which don't interfere with specificity, inheritance etc.

Also, if you'd add some variables using a class, while it is possible, that would mean that you'll need to actually have a class. While if you could use one variable to bulk change a lot of other variables, it would be so much easier and powerful: you could target not only class, but any number of pseudoclasses, their combinations etc. You won't need to add a class where you could just target things using selectors.

**Comment by brunoais** [comment]
So you mean to go against the main design decision for variables in CSS?

**Comment by kizu** [comment]
Can you provide a quote for the “main design decision” you mention? And even if there was one it does not matter that it couldn't evolve into something that would be useful for more developers.

And I don't know what to reply to the rest of your comment, it seems that you don't understand me and I don't have time to elaborate on what I had already said and wrote in the article.

Conditions can be useful as a DRY way, when you'll need to have more control over what you'd like to achieve by changing a single variable. For things like theming it can be much easier to say “here we have a dark them, and there a light one” and then choose colors and values for other properties based on this one theming variable. There is no alternative for theming other than CSS variables, and conditions could help tremendously in implementing theming (as the only alternative to them is to set all the variables you could need for any given theme). And there is already a way to make simple conditions. It is there, using calculations. It works, but it is ugly, is not completely supported and won't work for a lot of cases. But for a lot of cases it would work, and people would use it, and it there'd been a native way to do it, then people would use it.

**Comment by brunoais** [comment]
The CSS spec clearly states, in many of the features CSS has, specially 
in many CSS4 features, deliberate design limitations in 
pesudo-functions. Do you need citations?

Picking on the example, why not choose the theme based on a class in the 
`<html>` tag?

Also, there's no guarantee that these kinds of things will continue to 
work in the future. It is part of CSS' design not to have conditionals 
even though they can "pseudly" be made. Variables are great for DRY, no 
doubt about that, but should there be conditionals in CSS, even if 
through a hack?
I seriously think not.

I got your POV now and I have mine. I guess we will always disagree, then.
If you want to continue the discussion, I will, though.

**Comment by brunoais** [comment]
Check this example for theming:

	:root {
		--var-extra: #aaaaa;
		--var-main1: #aaaaa;
		--var-main2: #aaabb;
	}
	html.lightTheme {
		--var-main1: #ffffff;
		--var-main2: #ffffee;
	}
	html.darkTheme {
		--var-main1: #000000;
		--var-main2: #000011;
	}
	
	aTag {
		background-color: var(--var-main1);
		color: var(--var-main2);
	}

Why not do like that? Why use conditions?

**Comment by kizu** [comment]
Yes, I need citations, especially when you state things like “It is part of CSS' design not to have conditionals” which seems untrue (they can always become a part of CSS).

In regards to theming: I'm talking about not the theme for the whole site, but for parts of it, when one part can have a certain theme, another — another theme, and parts with different themes can be nested one into another. And without conditions you need to set everything for the theme only at the theme “definition”, and you can't decide on per-component basis how it should look like based on this theme.

Look at this example: https://codepen.io/kizu/pen/PjbKmN

There we need to declare all the values for different properties right at the theme definition. This is ok when we have not a lot of such properties or if we have an unlimited number of themes and need to define them often. That's ok, sure.

But! If we need to have a limited number of them and don't need to introduce new ones that often, and on the other hand we have a lot of elements we need to style and each of them could have different grades of a certain color, or even have a completely different color that fits that theme better, then it becomes really cumbersome to define all of that right at the theme definition.

What I'd want there is to define only the fact that we have a dark or a light theme at the theme definition, and then later we could have each component to decide which color it would want at which theme. It would mean our components would be decoupled from the theme definition and the theme would be kind of this component's API of sorts.

Without conditions this is impossible.
