### ISSUE TITLE
What do you think about this ;)

### ISSUE THREAD

**Issue by sylvain-** [kizu/kizu.github.com#194]
<style>
         label:hover{
            outline : 1px solid red;
         }

         #input_hidden{
            position   : absolute;
            border     : none;
            padding    : 0;
            max-width  : 0;
            max-height : 0;
         }

         #input_hidden:hover + p span.highlight{
            outline    : 1px solid #000;
            background : #FF0;
         }
      </style>
      <input id="input_hidden">
      <p>
         Lorem ipsum <span class="highlight">dolor</span> sit amet, consectetur adipisicing elit.<br/>
         Adipisci <span class="highlight">eius</span> modi perspiciatis<br/>
         <span class="highlight">praesentium</span> provident qui quibusdam rem.<br/>
         Ab atque ducimus, <span class="highlight">laudantium</span>, natus nesciunt<br/>
         officiis <span class="highlight">omnis</span> perspiciatis quia ratione, <span class="highlight">tempore</span>
         voluptate.<br/>
      </p>
      <label for="input_hidden">hover me</label>

**Comment by kizu** [comment]
Yep, that's also a way (and for such highlight — a better one). The example in the article was more to demonstrate what is possible, in cases when you don't have control over parent, have multiple similar filters, have elements in different containers without knowledge if they have a common parent etc. the way described in the article could be better (if it was valid and been supported by specs)
