### ISSUE TITLE
Feedback for “Keyboard-Only Focus”

### ISSUE THREAD

**Issue by simevidas** [kizu/kizu.github.com#196]
In the “Current State of the Problem” section [1], when I hover, click, or TAB through the three buttons, I see no difference in behavior between Chrome and Firefox (on Windows). Could you explain why it says **No** in the Firefox-Button cell? Does the green border not render when you click on the first button in Firefox? It does for me in both stable and Nightly.

[1]: http://kizu.ru/en/blog/keyboard-only-focus/#current-state-of-the-problem

**Comment by kizu** [comment]
Yep, it seems I didn't test enough in Firefox for Windows, and there were some problems there. I've updated the post with a better proper solution, as well mentioned the difference between the Mac and Win versions of Fx at the table. Thanks for the report!
