### ISSUE TITLE
Отзыв на «Только по-английски»

### ISSUE THREAD

**Issue by ademaro** [kizu/kizu.github.com#204]
В сафари странно выглядит длинное тире, как будто без пробелов до и после него: https://yadi.sk/i/_d6_t3P63ShRVo

**Comment by kizu** [comment]
Ага, спасибо, сейчас переделываю вёрстку сайта потихоньку, попробую это учесть там.

**Comment by kizu** [comment]
В новой версии вроде этой проблемы нет.
