### ISSUE TITLE
Отзыв на «Текстовый курсор»

### ISSUE THREAD

**Issue by stanpro** [kizu/kizu.github.com#206]
У меня более двух языков и трудно определить, какой текущий. Смотреть на угол экрана не удобно. Привязка к мыши еще хуже, теперь надо искать курсор по всему экрану.

Меня бы устроил значок языка на текстовом курсоре в ОС. Не попадалось ли такое?

**Comment by kizu** [comment]
Сомневаюсь, что такое возможно как что-то глобальное, так как это должно поддерживаться и на уровне ОС, и на уровне конкретных приложений, что вряд ли когда случится.

Из решений, которые выглядели интересно: вешать переключение раскладки на капслок (с горящей лампочкой для одного из вариантов), но более чем двух языков это не ок. И ещё решение — рамочка по всему экрану — чтоб уж точно сделать это заметным.
