### ISSUE TITLE
Feedback for "Counters and Stones"

### ISSUE THREAD

**Issue by ByteEater-pl** [kizu/kizu.github.com#223]
I think i would be easier to work with counters represented in unary. It's possible with https://www.w3.org/TR/css-counter-styles-3/#counter-style-system. In CR, but not widely implemented yet.

**Comment by kizu** [comment]
Yep! I did try this at the time, but sadly only Firefox supported it, and I think the support didn't move in any way.

Custom symbols that can consist of multiples could be really nicely used like this for example: https://codepen.io/kizu/pen/MPRrap (first example works only in Chrome and is basically incorrect, second — in Firefox)
